name: 'tacotron2'
encoder_n_convolutions: 3
encoder_embedding_dim: 512
encoder_kernel_size: 5
n_mel_channels: 80
n_frames_per_step: 1
decoder_rnn_dim: 1024
prenet_dim: 256
max_decoder_steps: 1000
gate_threshold: 0.5
p_attention_dropout: 0.1
p_decoder_dropout: 0.1

attention_rnn_dim: 1024
attention_dim: 128
attention_location_n_filters: 32
attention_location_kernel_size: 31

postnet_embedding_dim: 512
postnet_kernel_size: 5
postnet_n_convolutions: 5

mask_padding: True

n_symbols: 72
symbols_embedding_dim: 512

weight_decay: 1e-6
lr: 1e-3